# Generated by Django 3.1.7 on 2021-03-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='power',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_type',
            field=models.CharField(choices=[('Roundtrip', 'Round Trip'), ('One way', 'Oneway Trip')], default='Roundtrip', max_length=50),
        ),
    ]
